### PR TITLE
PDS4 Information Model Release 1.20.0.0

### PR DESCRIPTION
**Pull request by pds-ops**
Automated tagging of repo for nominal release of sub-model for PDS4 Release 1.20.0.0

### CODE REVIEW

**Comment by jordanpadams** [comment]
@thareUSGS looks like there was a failure here too regarding some `Component` class.

**Comment by thareUSGS** [comment]
@jordanpadams Both the component errors are from references to other LDDs. For example, this LDD references "IMG" and CART references "GEOM". Those looked properly linked in the repos and nothing has changed. I'm not sure how to fix this ...

here is the linked reference: https://github.com/pds-data-dictionaries/ldd-msss_cam_mh/tree/main/src/dependencies

Maybe the build order needs to be changed or something -- meaning first build IMG and then this?

**Comment by jordanpadams** [comment]
@thareUSGS hmmm, it actually pulls what is on main and builds the dependent LDDs before building the current repos. will play around to see what is up.

**Comment by jordanpadams** [comment]
@thareUSGS looks like it is a bug in LDDTool. standby. https://github.com/NASA-PDS/pds4-information-model/issues/661

**Comment by jordanpadams** [comment]
@thareUSGS these should all be fixed. i kicked off the LDD generation and all appear to have run successfully. feel free to review and merge.

**Pull request merged**
